apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
  labels:
    rht-gitops.com/janus-argocd: andrew-app-dev-build
  name: andrew-app-run-remediate
  namespace: andrew-app-dev
spec:
  params:
  - default: master
    description: The git revision
    name: git-revision
  - description: The repo url
    name: git-repo-url
  - default: quay-zdwn2.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com/quayadmin/andrew-app
    description: reference of the image that will get created
    name: output-image
  - description: Email of user who committed the change
    name: git-committer
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: andrew-app-run-build-
      labels:
        backstage.io/kubernetes-id: andrew-app
    spec:
      params:
      - name: source-repo
        value: $(tt.params.git-repo-url)
      - name: source-branch
        value: $(tt.params.git-revision)
      - name: output-image
        value: $(tt.params.output-image)
      - name: sonarqube-host-url
        value: https://sonarqube-sonarqube.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com
      - name: sonarqube-project-key
        value: andrew-app
      - name: sonarqube-project-secret
        value: andrew-app-sonarqube-secret
      - name: cyclonedx-host-url
        value: https://cyclonedx-bom-repo-server-cyclonedx.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com
      - name: stackrox-endpoint
        value: central-stackrox.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com:443
      - name: stackrox-secret
        value: andrew-app-stackrox-token
      - name: git-host
        value: gitlab-gitlab.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com
      - name: git-owner
        value: development
      - name: component-id
        value: andrew-app
      - name: common-password-secret
        value: common-password-secret
      - name: rekor-url
        value: http://rekor-server.trusted-artifact-signer.svc
      - name: tuf-mirror
        value: http://tuf.trusted-artifact-signer.svc
      - name: certificate-identity
        value: $(tt.params.git-committer)
      - name: oidc-issuer
        value: https://keycloak-rhsso.apps.cluster-zdwn2.zdwn2.sandbox2790.opentlc.com/auth/realms/openshift
      pipelineRef:
        name: andrew-app-build
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - emptyDir: {}
        name: reports
      - name: source-folder
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - emptyDir: {}
        name: maven-settings
      - name: docker-config
        secret:
          secretName: andrew-app-registry-creds
