apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: spring-boot-example
  namespace: konflux-app-spring-boot
spec:
  componentName: spring-boot-example
  application: spring-boot-example
  source:
    git:
      url: https://github.com/lzspangler/spring-boot-example.git
      revision: main
