apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
wata:
  config.json: |-
    {
      "platform": "github",
      "repositories": [
        "lzspangler/spring-boot-example"
      ],
      "onboarding": false,
      "requireConfig": "ignored",
      "extends": [
        "config:base"
      ],
      "baseBranches": ["main"]
    }
